# my global config
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["172.31.40.178:9100"]

  - job_name: "Ansible_1"
    static_configs:
      - targets: ["172.31.47.134:9100"]


  - job_name: "Ansible_2"
    static_configs:
      - targets: ["172.31.42.167:9100"]

  - job_name: "jenkins_server"
    static_configs:
      - targets: ["172.31.32.229:9100"]